name: Docker Build and Push

on:
  push:
    branches: ['**']
    tags-ignore: ['release-*']
    # # Publish semver tags as releases.
    # tags: ['release-v*.*.*']
  pull_request:
    branches: ['**']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  vars:
    name: Output build variables
    runs-on: ubuntu-latest
    outputs:
      appImage: ${{ fromJSON(steps.variables.outputs.result).appImage }}
      branch: ${{ fromJSON(steps.variables.outputs.result).branch }}
      imagePath: ${{ fromJSON(steps.variables.outputs.result).imagePath }}
    steps:
      - id: variables
        name: Script CI variables
        uses: actions/github-script@v4
        with:
          script: |
            const branch = context.ref.split('/').pop();
            const { REGISTRY, IMAGE_NAME } = process.env;
            const imagePath = `${REGISTRY}/${IMAGE_NAME}/${branch}`;
            const appImage = `${imagePath}/app`;
            core.info(`Commit to branch '${branch}'`);
            core.info(`Building docker image for '${appImage}'`);
            core.exportVariable('GITHUB_BRANCH_SLUG', branch);
            core.exportVariable('APP_IMAGE', appImage);
            return { branch, appImage, imagePath };

  build-latest-code:
    name: Docker build latest code
    runs-on: ubuntu-latest
    needs: vars
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set env variables
        run: |
          echo "APP_IMAGE=${{needs.vars.outputs.appImage}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{needs.vars.outputs.branch}}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker pull ${{ env.APP_IMAGE }}:latest || true
          echo "{\"commitRef\":\"${{ github.sha }}\",\"pipelineIID\":\"null\",\"pipelineUrl\":\"${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}\",\"buildNo\":\"$CI_PIPELINE_ID\",\"branchName\":\"${{ env.BRANCH_NAME }}\",\"registryImage\":\"${{ env.APP_IMAGE }}\"}" > version.json
          docker build --force-rm --cache-from ${{ env.APP_IMAGE }}:latest -t ${{ env.APP_IMAGE }}:latest -f docker/build.DockerFile .
          docker push ${{ env.APP_IMAGE }}:latest

  build-storybook:
    name: Docker build storybook
    runs-on: ubuntu-latest
    needs: vars
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set env variables
        run: |
          echo "STORYBOOK_IMAGE=${{needs.vars.outputs.imagePath}}/storybook" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker pull ${{ env.STORYBOOK_IMAGE}}:latest || true
          docker build --force-rm --cache-from ${{ env.STORYBOOK_IMAGE}}:latest -t ${{ env.STORYBOOK_IMAGE}}:latest -f docker/storybook.DockerFile .
          docker push ${{ env.STORYBOOK_IMAGE}}:latest
